using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SubTrackerTest1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void listBox2_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void subBtn_Click(object sender, EventArgs e)
        {
            this.subLstbx.Items.AddRange(new object[] { "Merina Zoeller",
            "A Nutty Milk Maid",
            "Abdirisaq Jama",
            "Abigail Hall",
            "Adam North",
            "Aisha Stern",
            "Alainna McCaa",
            "Albert Gonzales",
            "Alejandra Candela",
            "Alexis a Galvan",
            "Alexis Hill",
            "Allison Welty",
            "Alyssa Bearden",
            "Amanda Crane",
            "Andrea Herrera",
            "Andrew Swinford",
            "Angelica Enriquez",
            "Anna Johnson",
            "Anne Lapierre",
            "Arlene Verapen",
            "Ashley Bristol",
            "Ashley Fryer",
            "Astrid Arcane",
            "Autumn Bell",
            "Avon Independent Sales Rep",
            "Becky Schuett",
            "Beverly Thompson",
            "Billie Townsend",
            "Bradlee Boyd",
            "Bridget Webb",
            "Brittany Braddock",
            "Bryce Hoover",
            "Cameron Andes",
            "Candy Fisher",
            "Cara Jeffords",
            "Casey Horn",
            "Casey Vaught",
            "Catherine Nepomuceno",
            "Cea Herbert",
            "chabad",
            "Chad Humitz",
            "Charles Sibley",
            "Chase Holt",
            "Clyde Williams",
            "Cody Frazier",
            "Colleen Bolton",
            "Colleen Urban",
            "Corey Cook",
            "Courtney Fennell",
            "Cristina Ayala",
            "Cynthia Losito- Verschoor",
            "Daisy Longacre",
            "Dakota Troyer",
            "Daniel Bowen",
            "Daniel Westwood",
            "Deborah Anderson",
            "Dennis Creagh",
            "Desmond Zamora",
            "Devvin Kraatz",
            "Donna Logan",
            "Doss Haus",
            "Doulafleur",
            "Drones OK",
            "Dustin Bach",
            "Dusty Linville",
            "Dylan Frost",
            "Eaton Creations",
            "Edward Jacque",
            "Eligio Fernandez",
            "Elise Deckard",
            "Elizabeth Bailey",
            "Eric Gordon",
            "Eric Smith",
            "Erin Nott",
            "Evelyn Jones Jones",
            "Fluff and stuff",
            "Francisco Orozco",
            "Frank Holcher",
            "Frosted!",
            "Graham McKim",
            "Hanna Loadholtz",
            "Heather Ackerson",
            "Hebalife",
            "Jace McCoy",
            "Jackson Ingvardsen",
            "Jamie Sebastian",
            "Janet Lambert",
            "Jason Bicknell",
            "Jason Velazquez",
            "Jelena Blocker",
            "Jen Cole",
            "Jena Dipinto",
            "Jeniffer Contreras",
            "Jennifer Evans",
            "Jennifer McAlister",
            "Jennifer Natt",
            "Jeremiah Oddo",
            "Jeremy Jimenez",
            "Jeromy Nixon",
            "Jessica Beals",
            "Jessica Bishop",
            "Jessica Rutledge",
            "Jodi Pechonick",
            "John Rodriguez",
            "Joseph Batie",
            "Joseph Miranda",
            "Joshua Burns",
            "Joshua Taylor",
            "Justin Colburn",
            "Karen Petersen",
            "Kari Shaugobay",
            "Kate Adams",
            "Kathleen Grady",
            "Kathryn Debaker",
            "Kathryn Pentecost",
            "Kathy Loyd",
            "Kayla Barkley",
            "Kaylee Kuborn",
            "Keith Barney",
            "Kelly Keroack",
            "Kelsey Merchant",
            "Kenyetta Shepherd",
            "Keri Winter",
            "Kristen Stanik",
            "Kyra Griffith",
            "Lane Sakach",
            "Lawrence Repoza",
            "Leah Short",
            "Leesha Coleman",
            "Leigh Jamgochian",
            "Leilani Roberts",
            "Leo Regan",
            "Leshlie Robles",
            "Lindsay Darnell",
            "Lindsey White",
            "Lisa Hayes",
            "Luis Aponte",
            "Madelyn Fernandez",
            "Magdaleno Ceballos",
            "Margaret Kusko",
            "Margaret Stanfield",
            "Margarito Diaz Jr",
            "Mark Peters",
            "Marshall Lester",
            "Mary Lou Maxwell",
            "Mary Taylor",
            "Matthew Hidy",
            "Matthew McKee",
            "Matthew Weber",
            "Melinda Moody",
            "Michael Collins",
            "Michael Mathews",
            "Michael Reyes",
            "Mike Kinney",
            "Mike Mazza",
            "Morgan Glinski",
            "Nactali Rojas",
            "Nancy Bradford",
            "Natalie Murphy",
            "Natalie Pardo",
            "Nicholas Alcanter",
            "Nicholas Bishop",
            "Nicole Elgin",
            "Nicole Haag",
            "Nicole Piske",
            "Nicole Sites",
            "Noe Reyes",
            "Owlovely",
            "Pedro Gonzalez",
            "Penny Musick",
            "Peyton Pustmueller",
            "Prescillia Messa",
            "Priscilla Bariring",
            "Rainbow Bull Studios",
            "Raymond Lawrence Cabello",
            "Rebecca Brown",
            "Rebecca McKinney",
            "Regina Stovers",
            "Ridgley Chickens and Eggs",
            "Robyn Brunner",
            "Robyn Ferguson",
            "Ronnie Trimyer",
            "Rosaura Lowell",
            "RPM Computers",
            "Russell Dorsey",
            "Ryan Holley",
            "Sabrina Parsons",
            "Samuel Jake",
            "Sara Tkaczyk",
            "Sarah Daily",
            "Sarah Hawkins",
            "Sarah Smith",
            "Sean McHugh",
            "Seth Grundmeier",
            "Shannon Jordan",
            "Shelby Murdock",
            "Shon Williams",
            "Solana Lee",
            "Stephanie Goforth",
            "Steven Putman",
            "Sun Chic Designs",
            "Susana Ortiz",
            "Tammi Velez",
            "Tammy Hart",
            "Temera Johnson",
            "Thalassa Walter",
            "Thomas Hart",
            "Tia Churchill",
            "Tiffany & Cookie Co",
            "Timothy Roberts",
            "Tod Kromer",
            "Tortes and torts",
            "Tracy Kirchberger",
            "Vanessa Schmidt",
            "Veronica Manuel",
            "Vintage Addict Apparel Co",
            "Wajas",
            "Will Ingraham",
            "William Maddy",
            "Yanet Bobadilla",
            "Yesenia Sanchez",
            "Yselia",
            "Zac Conrad",
            "Zachary Endter",
            "Zachary Krumm",
            "Zanzibar Creek Stables"});

            if (subBtn.Enabled == true)
            {
                subBtn.Enabled = false;
            }
        }

        private void prodBtn_Click(object sender, EventArgs e)
        {
            this.prodLstbx.Items.AddRange(new object[] { "Bearing Bracket", "Brush Motor", "Feet", "Governor", "Hub/Bevel Gear", "Lock Lever", "Phase Control Board", "Power Cord", "Speed Control Lever", "Speed Control Plate", "Worm Follower Gear", "Factory Replacement Worm Gear", "https://www.webstaurantstore.com/" });

            if (prodBtn.Enabled == true)
            {
                prodBtn.Enabled = false;
            }
        }

        private void custBtn_Click(object sender, EventArgs e)
        {
            if (custBtn.Enabled == true)
            {
                custBtn.Enabled = false;
            }
        }
    }
}
